/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Address = () => {
  return (
    <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col self-stretch my-auto text-base max-md:mt-10">
        <h3 className="self-start font-semibold text-zinc-800">Address</h3>
        <address className="mt-9 font-medium text-slate-900 text-opacity-40">
          San Francisco, CA 560 Bush St & 20th Ave, Apt +1 555 333 44 22
        </address>
      </div>
    </div>
  );
};

export default Address;
