/**
 * This code was generated by Builder.io.
 */
import React from "react";

const GetStartedButton = () => {
  return (
    <div className="flex flex-col ml-5 w-[24%] max-md:ml-0 max-md:w-full">
      <button className="gap-4 self-stretch px-4 py-2.5 mt-7 w-full text-lg font-semibold text-white bg-indigo-600 rounded-lg max-md:mt-10">
        Get Started
      </button>
    </div>
  );
};

export default GetStartedButton;
