/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TryFBAFinance = () => {
  return (
    <div className="flex flex-col ml-5 w-[34%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow mt-6 text-base max-md:mt-10">
        <h3 className="self-start font-semibold text-zinc-800">
          Try FBA Finance
        </h3>
        <ul className="mt-9 font-medium text-slate-900 text-opacity-40">
          <li>Sign up and create your profile.</li>
          <li>Contribute to the funding pool.</li>
          <li>Take turns receiving funds.</li>
          <li>Grow your business without equity dilution.</li>
        </ul>
      </div>
    </div>
  );
};

export default TryFBAFinance;
